# Favicon
favicon: /favicon.ico

# SEO
keywords: 生活,博客,前端,游戏

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/chunqiuyiyu
  V2EX: https://www.v2ex.com/member/chunqiuyiyu

# Nav menu
menu:
  Home: /
  Archives: /archives
  About: /about